In [90]:
import numpy as np

In [91]:
def read_generalized_ising_hamiltonian(path):
    with open(path, "r") as f:
        f.readline()  # discard first line
        compressed_hamiltonian = [
            tuple(line.strip().split())
            for line in f.readlines()
        ]
    
    num_sites = len(compressed_hamiltonian[0][0])
    hamiltonian_terms = [np.zeros((num_sites,)*i) for i in range(num_sites+1)]

    for sites, val in compressed_hamiltonian:
        num_zs = 0
        site_nums = []
        for i, x in enumerate(sites):
            if x == 'z':
                site_nums.append(i)
                num_zs += 1

        hamiltonian_terms[num_zs][tuple(site_nums)] = float(val)

    return hamiltonian_terms

In [92]:
read_generalized_ising_hamiltonian("./hamiltonians/Ising-H2-STO-3G-bk-samespin-R=0.95.inp")

[array(-0.29573911),
 array([0.        , 0.13548245, 0.10890463, 0.15091995]),
 array([[ 0.        ,  0.        ,  0.10890463,  0.0154375 ],
        [ 0.        ,  0.        ,  0.        ,  0.15884487],
        [ 0.        ,  0.        ,  0.        , -0.15272731],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]),
 array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        , -0.1372898 ,  0.16529303],
         [ 0.        ,  0.        ,  0.        , -0.0154375 ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],
 
        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.15731721],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],
 
        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,

In [41]:
hamiltonian_terms = [np.zeros((num_sites,)*i) for i in range(num_sites+1)]

In [43]:
[x.shape for x in hamiltonian_terms]

[(), (4,), (4, 4), (4, 4, 4), (4, 4, 4, 4)]

In [89]:
hamiltonian_terms[0]

0.03775117547636375

In [38]:
np.zeros((4,))

array([0., 0., 0., 0.])

In [45]:
(1,) + (2,)

(1, 2)